### ISSUE TITLE
todo-env folder should not be commited to repository

### ISSUE THREAD

**Issue by benvinegar** [TatyCat/todoApp_TestScript#1]
AFAICT, this is populated by `pip` and shouldn't be committed.

Maybe it needs to be added to `.gitignore`.

**Comment by TatyCat** [comment]
todo-env/ added to .gitignore

**Comment by benvinegar** [comment]
It's back! Can we reopen this?

**Comment by TatyCat** [comment]
todo-env/ is in the .gitignore. Followed 'Remove Committed Files From Git Version Control' cache article and pushed.

Verified that todo-env/ is no longer visible in GitHub repo and closed issue.
