### ISSUE TITLE
Rename main test file and class name

### ISSUE THREAD

**Issue by benvinegar** [TatyCat/todoApp_TestScript#11]
We're not using pytest, but pytest does have a [test naming convention](https://docs.pytest.org/en/reorganize-docs/new-docs/user/naming_conventions.html) we could borrow:

> File names should start or end with “test”, as in test_example.py or example_test.py. If tests are defined as methods on a class, the class name should start with “Test”, as in TestExample. The class should not have an __init__ method.

For example, `test_todomvc.py`, and have the class name be `TestTodoMVC`.

**Comment by TatyCat** [comment]
This naming convention makes sense, as it it's a lot easier to read. Will update files
